import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Brain, Mail, Lock, User, Eye, EyeOff, CheckCircle2, XCircle, ArrowRight, X } from 'lucide-react'
import { authApi } from '../api/endpoints'
import { useAuth } from '../hooks/useAuth'
import { Spinner } from '../components/ui'

// Password rules used to validate account creation input
const passwordRules = [
  { id: 'length',  label: 'At least 8 characters',        test: (p: string) => p.length >= 8 },
  { id: 'upper',   label: 'One uppercase letter (A–Z)',    test: (p: string) => /[A-Z]/.test(p) },
  { id: 'lower',   label: 'One lowercase letter (a–z)',    test: (p: string) => /[a-z]/.test(p) },
  { id: 'number',  label: 'One number (0–9)',              test: (p: string) => /[0-9]/.test(p) },
  { id: 'special', label: 'One special character (!@#$…)', test: (p: string) => /[^A-Za-z0-9]/.test(p) },
]

// Modal displaying the platform's terms, privacy notes, and usage responsibilities
function TermsModal({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />

      {/* Modal */}
      <div className="relative bg-white rounded-card shadow-2xl w-full max-w-lg max-h-[80vh] flex flex-col">
        {/* Header */}
        <div className="section-header rounded-t-card flex items-center justify-between px-6 py-4 flex-shrink-0">
          <h2 className="font-display font-bold text-white text-xl">Terms & Conditions</h2>
          <button onClick={onClose} className="text-white/70 hover:text-white transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Scrollable content */}
        <div className="overflow-y-auto p-6 space-y-4 scrollbar-thin text-sm font-body text-bark-700 leading-relaxed">

          <p className="text-bark-500 italic text-xs">Last updated: February 2026</p>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">1. Purpose of MindEcho</h3>
            <p>MindEcho is an AI-assisted behavioral screening tool designed to help teachers and clinicians identify early indicators of ADHD in children. It is not a medical diagnostic tool and does not replace professional clinical assessment.</p>
          </section>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">2. Not a Medical Diagnosis</h3>
            <p>All results generated by MindEcho are AI-generated estimates based on behavioral data. These results must not be used as a formal diagnosis. Always consult a licensed healthcare professional before making any clinical decisions.</p>
          </section>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">3. Data Privacy</h3>
            <p>All data collected — including child information, video recordings, and assessment results — is stored locally on your device and is not transmitted to any third-party server. You are responsible for ensuring that data is handled in accordance with applicable privacy laws in your region.</p>
          </section>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">4. User Responsibilities</h3>
            <p>You agree to use MindEcho only for its intended educational and screening purposes. You must obtain appropriate consent from parents or guardians before conducting any assessment on a child. You are responsible for keeping your login credentials secure.</p>
          </section>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">5. Child Safety</h3>
            <p>MindEcho takes child safety seriously. Any recordings or personal information related to children must be handled with the utmost care and in compliance with child protection laws. Do not share assessment data with unauthorised individuals.</p>
          </section>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">6. Limitation of Liability</h3>
            <p>MindEcho and its developers are not liable for any decisions made based on the AI-generated screening results. The tool is provided "as is" for research and educational purposes only.</p>
          </section>

          <section>
            <h3 className="font-display font-bold text-bark-900 mb-1">7. Changes to Terms</h3>
            <p>These terms may be updated from time to time. Continued use of the platform constitutes acceptance of the revised terms.</p>
          </section>

          <p className="text-bark-400 text-xs pt-2 border-t border-cream-200">
            By creating an account you confirm that you have read, understood, and agree to these Terms & Conditions.
          </p>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-cream-200 flex-shrink-0">
          <button onClick={onClose} className="btn-green w-full">
            I Understand — Close
          </button>
        </div>
      </div>
    </div>
  )
}

// Registration page where new users create an account,
// review password requirements, and accept the terms and conditions.
export default function RegisterPage() {
  const navigate = useNavigate()
  const { login } = useAuth()

  const [fullName, setFullName]       = useState('')
  const [email, setEmail]             = useState('')
  const [password, setPassword]       = useState('')
  const [confirmPassword, setConfirm] = useState('')
  const [showPass, setShowPass]       = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const [agreed, setAgreed]           = useState(false)
  const [showTerms, setShowTerms]     = useState(false)
  const [error, setError]             = useState('')
  const [loading, setLoading]         = useState(false)

  const passOk    = passwordRules.every(r => r.test(password))
  const passMatch = password === confirmPassword && confirmPassword !== ''

  // Validate registration input, create the account, and sign the user in automatically
  const handleSignUp = async () => {
    setError('')
    if (!fullName.trim()) { setError('Please enter your full name.'); return }
    if (!email.trim())    { setError('Please enter your email address.'); return }
    const emailRegex = /^[^\s@]+@(gmail|yahoo|outlook|hotmail|icloud|live|msn|protonmail|me)\.(com|net|org|co\.uk|ae)$/i
    if (!emailRegex.test(email.trim())) { setError('Please enter a valid email address (e.g. Gmail, Yahoo, Outlook).'); return }
    if (!passOk)          { setError('Your password does not meet all the requirements below.'); return }
    if (!passMatch)       { setError('Passwords do not match. Please re-enter your password.'); return }
    if (!agreed)          { setError('Please agree to the Terms & Conditions to continue.'); return }

    setLoading(true)
    try {
      await authApi.register({
        full_name: fullName.trim(),
        email: email.trim().toLowerCase(),
        password,
      })
      await login(email.trim().toLowerCase(), password)
      navigate('/dashboard')
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Registration failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      {showTerms && <TermsModal onClose={() => setShowTerms(false)} />}

      <div className="min-h-screen bg-cream-100 flex items-center justify-center px-4 py-12">
        <div className="w-full max-w-md">

          <div className="text-center mb-6">
            <div className="inline-flex items-center justify-center w-14 h-14 bg-bark-800 rounded-2xl mb-3">
              <Brain size={28} className="text-cream-100" />
            </div>
            <div className="bg-primary-600 rounded-card px-6 py-3">
              <h1 className="font-display font-bold text-white text-2xl">Sign Up For Free</h1>
            </div>
          </div>

          <div className="card space-y-4">

            {/* Full name */}
            <div>
              <label className="label">Full Name</label>
              <div className="relative">
                <User size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-bark-400 pointer-events-none" />
                <input
                  type="text" className="input pl-10" placeholder="Your full name"
                  autoComplete="name" value={fullName}
                  onChange={e => setFullName(e.target.value)}
                />
              </div>
            </div>

            {/* Email */}
            <div>
              <label className="label">Email Address</label>
              <div className="relative">
                <Mail size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-bark-400 pointer-events-none" />
                <input
                  type="email" className="input pl-10" placeholder="your@email.com"
                  autoComplete="email" value={email}
                  onChange={e => setEmail(e.target.value)}
                />
              </div>
            </div>

            {/* Password */}
            <div>
              <label className="label">Password</label>
              <div className="relative">
                <Lock size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-bark-400 pointer-events-none" />
                <input
                  type={showPass ? 'text' : 'password'}
                  className="input pl-10 pr-10" placeholder="Create a strong password"
                  autoComplete="new-password" value={password}
                  onChange={e => setPassword(e.target.value)}
                />
                <button type="button"
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-bark-400 hover:text-bark-700"
                  onClick={() => setShowPass(v => !v)}>
                  {showPass ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>

              {password.length > 0 && (
                <div className="mt-2 space-y-1 bg-cream-100 rounded-btn p-3">
                  {passwordRules.map(r => {
                    const ok = r.test(password)
                    return (
                      <div key={r.id} className="flex items-center gap-2">
                        {ok
                          ? <CheckCircle2 size={13} className="text-primary-600 flex-shrink-0" />
                          : <XCircle      size={13} className="text-bark-300 flex-shrink-0" />
                        }
                        <span className={`text-xs font-body ${ok ? 'text-primary-700' : 'text-bark-400'}`}>
                          {r.label}
                        </span>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>

            {/* Confirm password */}
            <div>
              <label className="label">Confirm Password</label>
              <div className="relative">
                <Lock size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-bark-400 pointer-events-none" />
                <input
                  type={showConfirm ? 'text' : 'password'}
                  className={`input pl-10 pr-10 ${
                    confirmPassword.length > 0 ? (passMatch ? 'border-primary-500' : 'border-red-400') : ''
                  }`}
                  placeholder="Re-enter your password"
                  autoComplete="new-password" value={confirmPassword}
                  onChange={e => setConfirm(e.target.value)}
                />
                <button type="button"
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-bark-400 hover:text-bark-700"
                  onClick={() => setShowConfirm(v => !v)}>
                  {showConfirm ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              </div>
              {confirmPassword.length > 0 && (
                <p className={`text-xs mt-1 font-body ${passMatch ? 'text-primary-600' : 'text-red-500'}`}>
                  {passMatch ? '✓ Passwords match' : '✗ Passwords do not match'}
                </p>
              )}
            </div>

            {/* Terms checkbox */}
            <div className="flex items-start gap-2">
              <input
                type="checkbox"
                id="terms-checkbox"
                className="mt-0.5 accent-primary-600 cursor-pointer"
                checked={agreed}
                onChange={e => setAgreed(e.target.checked)}
              />
              <label htmlFor="terms-checkbox" className="text-sm text-bark-500 font-body cursor-pointer select-none">
                I agree with the{' '}
                <button
                  type="button"
                  className="text-primary-600 font-semibold underline hover:text-primary-700"
                  onClick={() => setShowTerms(true)}
                >
                  Terms & Conditions
                </button>
              </label>
            </div>

            {/* Error */}
            {error && (
              <div className="bg-red-50 border border-red-200 rounded-btn px-4 py-3 flex items-start gap-2">
                <XCircle size={16} className="text-red-500 flex-shrink-0 mt-0.5" />
                <p className="text-red-700 text-sm font-body">{error}</p>
              </div>
            )}

            <button
              type="button"
              className="btn-primary w-full"
              disabled={loading}
              onClick={handleSignUp}
            >
              {loading && <Spinner size={18} className="text-white" />}
              {loading ? 'Creating account...' : 'Sign Up'}
              {!loading && <ArrowRight size={18} />}
            </button>

            <div className="text-center space-y-1">
              <p className="text-bark-500 text-sm font-body">
                Already have an account?{' '}
                <Link to="/login" className="text-primary-600 font-semibold hover:underline">Sign In</Link>
              </p>
              <Link to="/forgot-password" className="text-bark-400 text-xs hover:text-primary-600 font-body underline block">
                Forgot Password?
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
